#include "textures.h"

void Textures_Load(void) {

	icon_app = oslLoadImageFilePNG("data/ic_fso_type_app.png", OSL_IN_RAM, OSL_PF_8888);
	icon_archive = oslLoadImageFilePNG("data/ic_fso_type_compress.png", OSL_IN_RAM, OSL_PF_8888);
	icon_audio = oslLoadImageFilePNG("data/ic_fso_type_audio.png", OSL_IN_RAM, OSL_PF_8888);
	icon_cd = oslLoadImageFilePNG("data/ic_fso_type_cdimage.png", OSL_IN_RAM, OSL_PF_8888);
	icon_dir = oslLoadImageFilePNG("data/ic_fso_folder.png", OSL_IN_RAM, OSL_PF_8888);
	icon_dir_dark = oslLoadImageFilePNG("data/ic_fso_folder_dark.png", OSL_IN_RAM, OSL_PF_8888);
	icon_file = oslLoadImageFilePNG("data/ic_fso_default.png", OSL_IN_RAM, OSL_PF_8888);
	icon_image = oslLoadImageFilePNG("data/ic_fso_type_image.png", OSL_IN_RAM, OSL_PF_8888);
	icon_prx = oslLoadImageFilePNG("data/ic_fso_type_system.png", OSL_IN_RAM, OSL_PF_8888);
	icon_text = oslLoadImageFilePNG("data/ic_fso_type_text.png", OSL_IN_RAM, OSL_PF_8888);
	icon_check = oslLoadImageFilePNG("data/btn_material_light_check_on_normal.png", OSL_IN_VRAM, OSL_PF_8888);
	icon_check_dark = oslLoadImageFilePNG("data/btn_material_light_check_on_normal_dark.png", OSL_IN_VRAM, OSL_PF_8888);
	icon_uncheck = oslLoadImageFilePNG("data/btn_material_light_check_off_normal.png", OSL_IN_VRAM, OSL_PF_8888);
	icon_uncheck_dark = oslLoadImageFilePNG("data/btn_material_light_check_off_normal_dark.png", OSL_IN_VRAM, OSL_PF_8888);
	icon_toggle_on = oslLoadImageFilePNG("data/btn_material_light_toggle_on_normal.png", OSL_IN_VRAM, OSL_PF_8888);
	icon_toggle_dark_on = oslLoadImageFilePNG("data/btn_material_light_toggle_on_normal_dark.png", OSL_IN_VRAM, OSL_PF_8888);
	icon_toggle_off = oslLoadImageFilePNG("data/btn_material_light_toggle_off_normal.png", OSL_IN_VRAM, OSL_PF_8888);
	icon_radio_off = oslLoadImageFilePNG("data/btn_material_light_radio_off_normal.png", OSL_IN_VRAM, OSL_PF_8888);
	icon_radio_on = oslLoadImageFilePNG("data/btn_material_light_radio_on_normal.png", OSL_IN_VRAM, OSL_PF_8888);
	icon_radio_dark_off = oslLoadImageFilePNG("data/btn_material_light_radio_off_normal_dark.png", OSL_IN_VRAM, OSL_PF_8888);
	icon_radio_dark_on = oslLoadImageFilePNG("data/btn_material_light_radio_on_normal_dark.png", OSL_IN_VRAM, OSL_PF_8888);
	icon_nav_drawer = oslLoadImageFilePNG("data/ic_material_light_navigation_drawer.png", OSL_IN_VRAM, OSL_PF_8888);
	icon_back = oslLoadImageFilePNG("data/ic_arrow_back_normal.png", OSL_IN_VRAM, OSL_PF_8888);
	options_dialog = oslLoadImageFilePNG("data/ic_material_options_dialog.png", OSL_IN_RAM, OSL_PF_8888);
	options_dialog_dark = oslLoadImageFilePNG("data/ic_material_options_dialog_dark.png", OSL_IN_RAM, OSL_PF_8888);
	properties_dialog = oslLoadImageFilePNG("data/ic_material_properties_dialog.png", OSL_IN_RAM, OSL_PF_8888);
	properties_dialog_dark = oslLoadImageFilePNG("data/ic_material_properties_dialog_dark.png", OSL_IN_RAM, OSL_PF_8888);
	dialog = oslLoadImageFilePNG("data/ic_material_dialog.png", OSL_IN_RAM, OSL_PF_8888);
	dialog_dark = oslLoadImageFilePNG("data/ic_material_dialog_dark.png", OSL_IN_RAM, OSL_PF_8888);
	battery_20 = oslLoadImageFilePNG("data/battery_20.png", OSL_IN_VRAM, OSL_PF_8888);
	battery_20_charging = oslLoadImageFilePNG("data/battery_20_charging.png", OSL_IN_VRAM, OSL_PF_8888);
	battery_30 = oslLoadImageFilePNG("data/battery_30.png", OSL_IN_VRAM, OSL_PF_8888);
	battery_30_charging = oslLoadImageFilePNG("data/battery_30_charging.png", OSL_IN_VRAM, OSL_PF_8888);
	battery_50 = oslLoadImageFilePNG("data/battery_50.png", OSL_IN_VRAM, OSL_PF_8888);
	battery_50_charging = oslLoadImageFilePNG("data/battery_50_charging.png", OSL_IN_VRAM, OSL_PF_8888);
	battery_60 = oslLoadImageFilePNG("data/battery_60.png", OSL_IN_VRAM, OSL_PF_8888);
	battery_60_charging = oslLoadImageFilePNG("data/battery_60_charging.png", OSL_IN_VRAM, OSL_PF_8888);
	battery_80 = oslLoadImageFilePNG("data/battery_80.png", OSL_IN_VRAM, OSL_PF_8888);
	battery_80_charging = oslLoadImageFilePNG("data/battery_80_charging.png", OSL_IN_VRAM, OSL_PF_8888);
	battery_90 = oslLoadImageFilePNG("data/battery_90.png", OSL_IN_VRAM, OSL_PF_8888);
	battery_90_charging = oslLoadImageFilePNG("data/battery_90_charging.png", OSL_IN_VRAM, OSL_PF_8888);
	battery_full = oslLoadImageFilePNG("data/battery_full.png", OSL_IN_VRAM, OSL_PF_8888);
	battery_full_charging = oslLoadImageFilePNG("data/battery_full_charging.png", OSL_IN_VRAM, OSL_PF_8888);
	battery_low = oslLoadImageFilePNG("data/battery_low.png", OSL_IN_VRAM, OSL_PF_8888);
	battery_unknown = oslLoadImageFilePNG("data/battery_unknown.png", OSL_IN_VRAM, OSL_PF_8888);
	wifi_off = oslLoadImageFilePNG("data/stat_sys_wifi_signal_off.png", OSL_IN_VRAM, OSL_PF_8888);
	wifi_on = oslLoadImageFilePNG("data/stat_sys_wifi_signal_on.png", OSL_IN_VRAM, OSL_PF_8888);
	usb_icon = oslLoadImageFilePNG("data/ic_material_light_usb.png", OSL_IN_VRAM, OSL_PF_8888);
	default_artwork = oslLoadImageFilePNG("data/default_artwork.png", OSL_IN_VRAM, OSL_PF_8888);
	btn_play = oslLoadImageFilePNG("data/btn_playback_play.png", OSL_IN_VRAM, OSL_PF_8888);
	btn_pause = oslLoadImageFilePNG("data/btn_playback_pause.png", OSL_IN_VRAM, OSL_PF_8888);
	btn_rewind = oslLoadImageFilePNG("data/btn_playback_rewind.png", OSL_IN_VRAM, OSL_PF_8888);
	btn_forward = oslLoadImageFilePNG("data/btn_playback_forward.png", OSL_IN_VRAM, OSL_PF_8888);
	btn_repeat = oslLoadImageFilePNG("data/btn_playback_repeat.png", OSL_IN_VRAM, OSL_PF_8888);
	btn_shuffle = oslLoadImageFilePNG("data/btn_playback_shuffle.png", OSL_IN_VRAM, OSL_PF_8888);
	btn_repeat_overlay = oslLoadImageFilePNG("data/btn_playback_repeat_overlay.png", OSL_IN_VRAM, OSL_PF_8888);
	btn_shuffle_overlay = oslLoadImageFilePNG("data/btn_playback_shuffle_overlay.png", OSL_IN_VRAM, OSL_PF_8888);
	bg_header = oslLoadImageFilePNG("data/bg_header.png", OSL_IN_VRAM, OSL_PF_8888);
	icon_sd = oslLoadImageFilePNG("data/ic_material_light_sdcard.png", OSL_IN_VRAM, OSL_PF_8888);
	icon_secure = oslLoadImageFilePNG("data/ic_material_light_secure.png", OSL_IN_VRAM, OSL_PF_8888);
	icon_sd_dark = oslLoadImageFilePNG("data/ic_material_light_sdcard_dark.png", OSL_IN_VRAM, OSL_PF_8888);
	icon_secure_dark = oslLoadImageFilePNG("data/ic_material_light_secure_dark.png", OSL_IN_VRAM, OSL_PF_8888);
}

void Textures_Free(void) {
	oslDeleteImage(icon_secure_dark);
	oslDeleteImage(icon_sd_dark);
	oslDeleteImage(icon_secure);
	oslDeleteImage(icon_sd);
	oslDeleteImage(bg_header);
	oslDeleteImage(btn_shuffle_overlay);
	oslDeleteImage(btn_repeat_overlay);
	oslDeleteImage(btn_shuffle);
	oslDeleteImage(btn_repeat);
	oslDeleteImage(btn_forward);
	oslDeleteImage(btn_rewind);
	oslDeleteImage(btn_pause);
	oslDeleteImage(btn_play);
	oslDeleteImage(default_artwork);
	oslDeleteImage(usb_icon);
	oslDeleteImage(wifi_on);
	oslDeleteImage(wifi_off);
	oslDeleteImage(battery_unknown);
	oslDeleteImage(battery_low);
	oslDeleteImage(battery_full_charging);
	oslDeleteImage(battery_full);
	oslDeleteImage(battery_90_charging);
	oslDeleteImage(battery_80_charging);
	oslDeleteImage(battery_80);
	oslDeleteImage(battery_60_charging);
	oslDeleteImage(battery_60);
	oslDeleteImage(battery_50_charging);
	oslDeleteImage(battery_50);
	oslDeleteImage(battery_30_charging);
	oslDeleteImage(battery_30);
	oslDeleteImage(battery_20_charging);
	oslDeleteImage(battery_20);
	oslDeleteImage(dialog_dark);
	oslDeleteImage(dialog);
	oslDeleteImage(properties_dialog_dark);
	oslDeleteImage(properties_dialog);
	oslDeleteImage(options_dialog_dark);
	oslDeleteImage(options_dialog);
	oslDeleteImage(icon_back);
	oslDeleteImage(icon_nav_drawer);
	oslDeleteImage(icon_radio_dark_on);
	oslDeleteImage(icon_radio_dark_off);
	oslDeleteImage(icon_radio_on);
	oslDeleteImage(icon_radio_off);
	oslDeleteImage(icon_toggle_off);
	oslDeleteImage(icon_toggle_dark_on);
	oslDeleteImage(icon_toggle_on);
	oslDeleteImage(icon_uncheck_dark);
	oslDeleteImage(icon_uncheck);
	oslDeleteImage(icon_check_dark);
	oslDeleteImage(icon_check);
	oslDeleteImage(icon_text);
	oslDeleteImage(icon_prx);
	oslDeleteImage(icon_image);
	oslDeleteImage(icon_file);
	oslDeleteImage(icon_dir_dark);
	oslDeleteImage(icon_dir);
	oslDeleteImage(icon_cd);
	oslDeleteImage(icon_audio);
	oslDeleteImage(icon_archive);
	oslDeleteImage(icon_app);
}
