name: C/C++ CI

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add build-base git bash cmake
    
    - name: Compile project
      run: make
    
    - uses: actions/upload-artifact@v3
      with:
        name: CMFileManager-PSP
        path: app/EBOOT.PBP
