name: C/C++ CI

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: krystalgamer/setup-psptoolchain@1.0
    - uses: actions/checkout@v2
    - name: Compile
      run: make
